---
- hosts: all
  become: yes
  vars_files:
  - variables
  tasks:
    - name: packages installation
      yum: 
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items: "{{ packages }}"

    - name: services and enable
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"

    - name: Ports in Firewalld
      firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
        with_items: "{{ ports }}"
